import type { Metadata } from "next";
import { Provider } from "react";
import "./globals.css";
import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
  title: "Inner Circle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TopNav />
      <body>{children}</body>
    </html>
  );
}
